name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'jp2tw-subs/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'jp2tw-subs/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jp2tw-subs
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install components
        run: rustup component add clippy rustfmt
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test --all --verbose
