name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build release
        run: cargo build --release
      - name: Archive artifact (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist
          BIN=jp2tw-captioner
          cp target/release/$BIN dist/$BIN-${{ runner.os }}-${{ runner.arch }}
          tar -C dist -czf $BIN-${{ runner.os }}-${{ runner.arch }}.tar.gz $BIN-${{ runner.os }}-${{ runner.arch }}
      - name: Archive artifact (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir dist
          set BIN=jp2tw-captioner.exe
          copy target\release\%BIN% dist\jp2tw-captioner-Windows-%PROCESSOR_ARCHITECTURE%.exe
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            jp2tw-captioner-*.tar.gz
            dist/jp2tw-captioner-Windows-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

